import type { FeedbackItem, WorkOrder, EmergencyException, Competitor, Requirement, KnowledgeItem, UserRole, ModelRankItem, MetricCardData } from '@/types';

// ==================== 反馈数据 ====================
export const feedbackData: FeedbackItem[] = [
  {
    id: 'CS-20260618-0001',
    mergeGroup: 'CS20A_POWER',
    source: '商品评论',
    createMode: 'AI自动创建',
    brand: '云康宝',
    site: 'Amazon.com (US)',
    productType: '体脂秤',
    model: 'CS20A',
    internal: 'YL-CS20A-8',
    asin: 'B0CS20AUS1',
    raw: 'Scale stopped working after 2 weeks. Screen went black and won\'t turn on even with new batteries.',
    ai: '体脂秤使用两周后无法开机，屏幕黑屏，更换电池无效。涉及产品稳定性问题。',
    level1: '产品质量',
    level2: '硬件问题',
    level3: '无法开机',
    sentiment: '负向',
    returned: '退货',
    exception: 'P2',
    processRoute: '待处理',
    processState: '待处理',
    feedbackUser: '张伟',
    handler: '李工',
    date: '2026-06-18',
  },
  {
    id: 'CS-20260618-0002',
    mergeGroup: 'CS20A_POWER',
    source: '退货原因',
    createMode: 'AI自动创建',
    brand: '云康宝',
    site: 'Amazon.com (US)',
    productType: '体脂秤',
    model: 'CS20A',
    internal: 'YL-CS20A-8',
    asin: 'B0CS20AUS1',
    raw: 'Device suddenly turned off during measurement. Tried different batteries, no luck.',
    ai: '测量过程中突然关机，更换电池无效，怀疑主板或供电模块故障。',
    level1: '产品质量',
    level2: '硬件问题',
    level3: '自动关机',
    sentiment: '负向',
    returned: '退货',
    exception: 'P2',
    processRoute: '转工单',
    processState: '处理中',
    feedbackUser: '王芳',
    handler: '李工',
    date: '2026-06-18',
  },
  {
    id: 'CS-20260617-0045',
    mergeGroup: 'CS30B_ACCURACY',
    source: '站内信',
    createMode: '人工录入',
    brand: '云康宝',
    site: 'Amazon.com (US)',
    productType: '体脂秤',
    model: 'CS30B',
    internal: 'YL-CS30B-2',
    asin: 'B0CS30BUS2',
    raw: 'Body fat percentage reading varies wildly - 25% one day, 32% the next. Inconsistent.',
    ai: '体脂率测量波动大，同一天测量结果差异超过7%，用户质疑准确性。',
    level1: '用户体验',
    level2: '测量精度',
    level3: '体脂率波动',
    sentiment: '负向',
    returned: '否',
    exception: 'P3',
    processRoute: '待处理',
    processState: '待处理',
    feedbackUser: '李四',
    handler: '王工',
    date: '2026-06-17',
  },
  {
    id: 'CS-20260616-0120',
    mergeGroup: 'CS20A_APP',
    source: 'APP反馈',
    createMode: 'AI自动创建',
    brand: '云康宝',
    site: 'Amazon.com (US)',
    productType: '体脂秤',
    model: 'CS20A',
    internal: 'YL-CS20A-8',
    asin: 'B0CS20AUS1',
    raw: 'App keeps disconnecting after latest iOS update. Have to pair again every time.',
    ai: 'iOS系统更新后APP频繁断连，每次使用需重新配对，用户反馈体验差。',
    level1: '软件问题',
    level2: '连接稳定性',
    level3: '蓝牙断连',
    sentiment: '负向',
    returned: '否',
    exception: 'P3',
    processRoute: '转需求',
    processState: '已转需求',
    feedbackUser: 'Emma',
    handler: '陈工',
    date: '2026-06-16',
  },
  {
    id: 'CS-20260615-0089',
    mergeGroup: 'MG20_NOISE',
    source: '商品评论',
    createMode: 'AI自动创建',
    brand: '云康宝',
    site: '天猫',
    productType: '筋膜枪',
    model: 'MG20',
    internal: 'YL-MG20-3',
    asin: 'N/A',
    raw: '噪音太大了，比宣传的大很多，用了两次就不想用了。',
    ai: '筋膜枪噪音过大，与宣传不符，用户因噪音问题放弃使用，体验差。',
    level1: '产品质量',
    level2: '噪音问题',
    level3: '电机噪音',
    sentiment: '负向',
    returned: '退货',
    exception: 'P2',
    processRoute: '转工单',
    processState: '处理中',
    feedbackUser: '赵六',
    handler: '刘工',
    date: '2026-06-15',
  },
  {
    id: 'CS-20260614-0033',
    mergeGroup: 'BF511_BATTERY',
    source: '客服沟通',
    createMode: '人工录入',
    brand: '云康宝',
    site: '京东',
    productType: '人体秤',
    model: 'BF511',
    internal: 'YL-BF511-1',
    asin: 'N/A',
    raw: '买了一个月电池盖就裂了，客服让寄回去检测，太麻烦了。',
    ai: '使用一个月电池盖开裂，客服建议返厂检测但用户认为流程繁琐，体验差。',
    level1: '产品质量',
    level2: '外观问题',
    level3: '外壳开裂',
    sentiment: '负向',
    returned: '否',
    exception: 'P3',
    processRoute: '直接回复关闭',
    processState: '已关闭',
    feedbackUser: '刘洋',
    handler: '孙工',
    date: '2026-06-14',
  },
  {
    id: 'CS-20260613-0007',
    mergeGroup: 'GE31002_GLASS',
    source: '社媒',
    createMode: 'AI自动创建',
    brand: '云康宝',
    site: 'Amazon.com (US)',
    productType: '八电极秤',
    model: 'GE31002B1',
    internal: 'YL-GE31002B1-CS',
    asin: 'B0GE31002B1',
    raw: 'Glass cracked after 3 months. Dangerous! Shards everywhere. Packaging looked fine on arrival.',
    ai: '使用三个月后玻璃面板碎裂，存在安全隐患。到货时包装完好，怀疑钢化玻璃质量问题。',
    level1: '产品质量',
    level2: '安全问题',
    level3: '玻璃碎裂',
    sentiment: '负向',
    returned: '退货',
    exception: 'P1',
    processRoute: '转异常',
    processState: '异常处理中',
    feedbackUser: 'John',
    handler: '陈总',
    date: '2026-06-13',
  },
];

// ==================== 工单数据 ====================
export const workOrderData: WorkOrder[] = [
  {
    id: 'TK-20260611-0342',
    summary: '体脂测量不稳定问题排查',
    relatedFeedback: 'FB-20260611-00122',
    feedbackIds: ['FB-20260611-00122'],
    status: '处理中',
    owner: '王工',
    dept: '产品部',
    sla: '18h 22m',
    result: '分析测量日志',
    closeReason: '-',
    exception: '否',
    requirement: '预留',
    step: 3,
  },
  {
    id: 'TK-20260610-0321',
    summary: 'AMAZON-US站点体脂秤退货率飙升分析',
    relatedFeedback: 'FB-20260610-00045',
    feedbackIds: ['FB-20260610-00045', 'FB-20260610-00056'],
    status: '待处理',
    owner: '赵工',
    dept: '质量部',
    sla: '4h 15m',
    result: '-',
    closeReason: '-',
    exception: '是',
    requirement: '否',
    step: 1,
  },
  {
    id: 'TK-20260609-0298',
    summary: '筋膜枪MG20电机异响处理',
    relatedFeedback: 'FB-20260609-00012',
    feedbackIds: ['FB-20260609-00012'],
    status: '已完成',
    owner: '刘工',
    dept: '产品部',
    sla: '已完成',
    result: '更换电机供应商，提升质检标准',
    closeReason: '问题闭环',
    exception: '否',
    requirement: '否',
    step: 5,
  },
];

// ==================== 异常数据 ====================
export const emergencyData: EmergencyException[] = [
  {
    id: 'P1-20260611-008',
    level: 'P1',
    region: '海外',
    site: 'Amazon',
    productLine: '八电极秤',
    internal: 'GE31002B1-CS',
    creator: '陈晨',
    dimension: '平台合规',
    source: '投诉/舆情',
    deadline: '已超时 2h',
    reminderLimit: '2h',
    reminderDeadline: '2026-06-05 12:00',
    overdue: true,
    owner: '陈总',
    team: '海外运营+产品经理',
    status: '临时方案超时',
    issue: '玻璃碎裂投诉连续上升',
    impactScope: 'GE31002B1-CS 批次2026Q1',
    action: '隔离相关批次，检查包装防护',
    feedback: 'CS-20260613-0007（2条数据）',
    tempPlan: '',
    rootCause: '待根因分析',
    fixPlan: '待整改措施',
    verifyResult: '待验证',
    step: 0,
  },
  {
    id: 'P2-20260610-015',
    level: 'P2',
    region: '海外',
    site: 'Amazon',
    productLine: '体脂秤',
    internal: 'YL-CS20A-8',
    creator: '张伟',
    dimension: '产品质量',
    source: '退货分析',
    deadline: '3h 15m',
    reminderLimit: '4h',
    reminderDeadline: '2026-06-10 17:00',
    overdue: false,
    owner: '王工',
    team: '产品+品质',
    status: '处理中',
    issue: 'CS20A开机故障集中反馈',
    impactScope: 'CS20A 2026Q2 批次',
    action: '复现测试，排查主板批次',
    feedback: 'CS-20260618-合并（2条数据）',
    tempPlan: '已输出临时方案',
    rootCause: '正在分析',
    fixPlan: '待整改措施',
    verifyResult: '待验证',
    step: 1,
  },
];

// ==================== 需求数据 ====================
export const requirementData: Requirement[] = [
  {
    id: 'REQ-20260616-0001',
    title: 'APP蓝牙连接优化（iOS 18适配）',
    source: '反馈 CS-20260616-0120',
    priority: '高',
    status: '开发中',
    owner: '陈工',
    dept: '研发部',
    date: '2026-06-16',
    description: 'iOS 18系统更新导致蓝牙连接不稳定，需适配新版Core Bluetooth API。',
  },
  {
    id: 'REQ-20260610-0003',
    title: '体脂率算法优化',
    source: '反馈 CS-20260617-0045',
    priority: '中',
    status: '待评估',
    owner: '李工',
    dept: '算法组',
    date: '2026-06-10',
    description: 'CS30B型号体脂率测量波动过大，需优化电极信号处理算法。',
  },
  {
    id: 'REQ-20260605-0012',
    title: '增加多用户数据隔离功能',
    source: '产品规划',
    priority: '中',
    status: '待排期',
    owner: '王工',
    dept: '产品部',
    date: '2026-06-05',
    description: '支持一台设备多人使用，数据独立存储和切换。',
  },
];

// ==================== 竞品数据 ====================
export const competitorData: Competitor[] = [
  {
    name: 'Withings Body Scan',
    asin: 'B0WITHINGS',
    line: '八电极秤',
    price: '$349.95',
    channels: 'Amazon / 独立站',
    params: '分段身体成分 / 心率 / 血管年龄 / 高端健康管理',
  },
  {
    name: 'Eufy Smart Scale P3',
    asin: 'B0EUFYP3',
    line: '体脂秤',
    price: '$79.99',
    channels: 'Amazon / BestBuy',
    params: '3D体态建模 / 16项身体数据 / 宠物模式 / AI饮食建议',
  },
  {
    name: 'Renpho Elis 1',
    asin: 'B0RENPHO',
    line: '体脂秤',
    price: '$29.99',
    channels: 'Amazon',
    params: '13项身体指标 / 无限用户 / 婴儿模式 / FSA/HSA报销',
  },
];

// ==================== Q&A 知识库 ====================
export const knowledgeData: KnowledgeItem[] = [
  {
    id: 'QA-001',
    question: '体脂秤无法开机怎么办？',
    answer: '1. 检查电池是否安装正确（正负极方向）；2. 更换新电池；3. 长按电源键10秒重置；4. 如仍无法开机请联系售后。',
    category: '硬件故障',
    tags: ['CS20A', 'CS30B', '开机'],
    date: '2026-06-01',
  },
  {
    id: 'QA-002',
    question: 'APP连接不上秤怎么办？',
    answer: '1. 确保手机蓝牙已开启；2. 将秤放在平坦地面；3. 关闭APP后重新打开；4. 在手机设置中忽略设备后重新配对；5. 检查APP版本是否为最新。',
    category: '连接问题',
    tags: ['蓝牙', 'APP', '连接'],
    date: '2026-06-08',
  },
  {
    id: 'QA-003',
    question: '体脂率测量不准确？',
    answer: '1. 确保赤脚站在电极片上；2. 双脚保持干燥；3. 每天同一时间测量；4. 避免饭后/运动后立即测量；5. 如持续偏差请联系客服。',
    category: '测量问题',
    tags: ['体脂率', '准确性', '校准'],
    date: '2026-06-12',
  },
];

// ==================== 用户角色 ====================
export const userRoleData: UserRole[] = [
  { key: 'admin', name: '管理员', label: '管理员', scope: 'all', avatar: 'AD' },
  { key: 'cm_mgr', name: '筋膜枪产品经理', label: '筋膜枪产品经理', scope: 'line:CM', avatar: 'CM' },
  { key: 'cs_mgr', name: '体脂秤产品经理', label: '体脂秤产品经理', scope: 'line:CS', avatar: 'CS' },
  { key: 'overseas', name: '海外运营', label: '海外运营', scope: 'region:海外', avatar: 'OS' },
  { key: 'domestic', name: '国内运营', label: '国内运营', scope: 'region:国内', avatar: 'DM' },
];

// ==================== 仪表盘 ====================
export const metricCards: MetricCardData[] = [
  { key: 'returnRate', label: '退货率', value: '3.2%', change: '+0.5%', trend: 'up', formula: '退货数 / 总销量 × 100%' },
  { key: 'feedbackRate', label: '反馈率', value: '8.7%', change: '-1.2%', trend: 'down', formula: '反馈数 / 总销量 × 100%' },
  { key: 'closeRate', label: '闭环率', value: '76.5%', change: '+3.8%', trend: 'up', formula: '已关闭数 / 总反馈数 × 100%' },
  { key: 'responseRate', label: '响应达成率', value: '92.1%', change: '+5.3%', trend: 'up', formula: 'SLA内响应数 / 需响应总数 × 100%' },
  { key: 'exceptionRate', label: '异常占比', value: '4.5%', change: '-0.8%', trend: 'down', formula: '异常反馈数 / 总反馈数 × 100%' },
  { key: 'negativeRate', label: '差评率', value: '12.3%', change: '+1.1%', trend: 'up', formula: '差评数 / 总评价数 × 100%' },
];

export const modelRankData: ModelRankItem[] = [
  { model: 'CS20A', internal: 'YL-CS20A-8', material: 'CS20A-PCBA-V3', returnRate: '4.2%', feedbackRate: '10.5%', closeRate: '72%', responseRate: '88%', exceptionRate: '6.8%', negativeRate: '15.2%' },
  { model: 'CS30B', internal: 'YL-CS30B-2', material: 'CS30B-PCBA-V2', returnRate: '2.8%', feedbackRate: '7.1%', closeRate: '81%', responseRate: '95%', exceptionRate: '3.2%', negativeRate: '9.8%' },
  { model: 'BF511', internal: 'YL-BF511-1', material: 'BF511-PCBA-V1', returnRate: '1.5%', feedbackRate: '4.8%', closeRate: '90%', responseRate: '97%', exceptionRate: '1.1%', negativeRate: '5.4%' },
  { model: 'MG20', internal: 'YL-MG20-3', material: 'MG20-PCBA-V2', returnRate: '5.1%', feedbackRate: '12.3%', closeRate: '65%', responseRate: '82%', exceptionRate: '8.5%', negativeRate: '18.7%' },
  { model: 'GE31002B1', internal: 'YL-GE31002B1-CS', material: 'GE31002B1-PCBA-V1', returnRate: '3.6%', feedbackRate: '9.2%', closeRate: '78%', responseRate: '91%', exceptionRate: '5.2%', negativeRate: '11.3%' },
];

// ==================== 筛选选项 ====================
export const timeOptions = ['近7天', '近30天', '近90天', '自定义'];
export const siteOptions = ['全部站点', 'Amazon.com (US)', '天猫', '京东', '抖音'];
export const brandOptions = ['全部品牌', '云康宝', 'AF', 'GE', 'LF'];
export const productTypeOptions = ['全部产品类型', '体脂秤', '人体秤', '八电极秤', '筋膜枪', '按摩产品'];
export const modelOptions = ['全部', 'CS20A', 'CS30B', 'BF511', 'MG20', 'MS30'];
export const sourceOptions = ['全部', '商品评论', '退货原因', '站内信', '客服沟通', 'APP反馈', '社媒', 'Vine', '天使用户', '投诉/警告'];
export const feedbackTabOptions: { key: string; label: string; count: number }[] = [
  { key: 'all', label: '全部', count: 3842 },
  { key: 'pending', label: '待处理', count: 156 },
  { key: 'review', label: '待人工复核', count: 42 },
  { key: 'done', label: '已处理', count: 3644 },
];
