import type {
    FeedbackItem,
    WorkOrder,
    EmergencyException,
    Competitor,
    CandidateLead,
    RequirementPoolItem,
    UserRole,
    Report,
    KnowledgeItem,
    TabOption,
    TemplateConfig,
} from '@/types';

// ========== 选项数据 ==========
export const siteOptions = ['Amazon.com (US)', '天猫', '京东', '抖音'];
export const feedbackTabOptions: TabOption[] = [
    { key: 'all', label: '全部' },
    { key: 'pending', label: '待处理' },
    { key: 'review', label: '待人工复核' },
    { key: 'done', label: '已处理' },
    { key: 'mine', label: '我反馈的' },
];
export const processRouteOptions = [
    '待处理',
    '已转工单',
    '已转需求',
    '已转异常',
    '已转Q&A',
    '已直接回复关闭',
];
export const processStateOptions = ['待人工复核', '待处理', '已处理'];
export const returnOptions = ['否', '退货', '换货', '退货+换货', '待确认'];
export const exceptionLevels = ['P0', 'P1', 'P2', 'P3', '待确认', '否'];
export const sourceOptions = [
    '海外电商-退货反馈',
    '国内电商-退货反馈',
    '海外电商-商品评论',
    '国内电商-商品评论',
    '站内信',
    '客服沟通',
    'APP反馈',
];
export const timeOptions = ['最近7天', '最近30天', '本月', '本季度', '本年'];
export const brandOptions = ['云康宝', 'AF', 'LF'];
export const productTypeOptions = ['体脂秤', '筋膜枪', '血压计'];
export const modelOptions = ['CS20A', 'AF-30B', 'BP-02', 'MG20'];
export const emergencyStepLabels = ['发现异常', '临时方案', '根因分析', '整改措施', '验证结果'];
export const workOrderSteps = ['转工单', '分派责任人', '处理中', '待确认', '已闭环'];

// ========== 用户角色 ==========
export const roleOptions: UserRole[] = [
    { key: 'admin', name: '管理员', label: '管理员', scope: 'all', avatar: 'AD' },
    { key: 'massagePm', name: '孙工', label: '筋膜枪产品经理', scope: 'line:CM', avatar: 'CM' },
    { key: 'scalePm', name: '李工', label: '八电极产品经理', scope: 'line:CS', avatar: 'CS' },
    {
        key: 'overseasFeedback',
        name: '张伟',
        label: '海外反馈人员',
        scope: 'region:海外',
        avatar: 'OS',
    },
    {
        key: 'domesticFeedback',
        name: '王雪',
        label: '国内反馈人员',
        scope: 'region:国内',
        avatar: 'CN',
    },
];

// ========== 模板 ==========
export const templateLibrary: TemplateConfig[] = [
    {
        name: '默认模板',
        values: {
            site: ['Amazon.com (US)'],
            brand: '云康宝',
            productType: '体脂秤',
            source: '商品评论',
            owner: '李工',
        },
    },
    {
        name: 'APP问题模板',
        values: {
            site: ['Amazon.com (US)', '天猫'],
            brand: 'AF',
            productType: '体脂秤',
            source: 'APP反馈',
            owner: '刘工',
        },
    },
    {
        name: '筋膜枪模板',
        values: {
            site: ['抖音', '京东'],
            brand: 'LF',
            productType: '筋膜枪',
            source: '商品评论',
            owner: '孙工',
        },
    },
];

// ========== 反馈数据（与原始数据完全一致） ==========
export const feedbackData: FeedbackItem[] = [
    {
        id: 'CS-20260618-0001',
        mergeGroup: 'CS20A_POWER',
        source: '商品评论',
        createMode: 'AI自动创建',
        brand: '云康宝',
        site: 'Amazon.com (US)',
        productType: '体脂秤',
        model: 'CS20A',
        internal: 'YL-CS20A-8',
        asin: 'B0CS20AUS1',
        raw: 'Scale stopped powering on after two weeks, replacing batteries did not help.',
        ai: '体脂秤使用两周后无法开机，更换电池无效。',
        level1: '产品质量',
        level2: '硬件问题',
        level3: '无法开机',
        sentiment: '负向',
        returned: '退货',
        exception: 'P2',
        processRoute: '待处理',
        processState: '待处理',
        feedbackUser: '张伟',
        handler: '李工',
        date: '2026-06-18',
    },
    {
        id: 'CS-20260618-0002',
        mergeGroup: 'CS20A_POWER',
        source: '退货原因',
        createMode: 'AI自动创建',
        brand: '云康宝',
        site: 'Amazon.com (US)',
        productType: '体脂秤',
        model: 'CS20A',
        internal: 'YL-CS20A-8',
        asin: 'B0CS20AUS1',
        raw: 'Customer returned the scale because it could not turn on after battery replacement.',
        ai: '客户因更换电池后仍无法开机而退货。',
        level1: '产品质量',
        level2: '硬件问题',
        level3: '无法开机',
        sentiment: '负向',
        returned: '退货',
        exception: 'P2',
        processRoute: '已转工单',
        processState: '已处理',
        feedbackUser: '李娜',
        handler: '系统',
        date: '2026-06-18',
    },
    {
        id: 'CS-20260617-0003',
        source: 'APP反馈',
        createMode: 'AI自动创建',
        brand: 'AF',
        site: 'Amazon.com (US)',
        productType: '体脂秤',
        model: 'AF-30B',
        internal: 'AF-CS30B-CN',
        asin: 'B0AF30BUS1',
        raw: '用户反馈体脂率数据与健身房设备差异较大，希望确认算法。',
        ai: '体脂率数据偏差较大，需要复核算法或测量引导。',
        level1: '产品体验',
        level2: '数据准确性',
        level3: '测脂不准',
        sentiment: '负向',
        returned: '否',
        exception: '待确认',
        processRoute: '待处理',
        processState: '待人工复核',
        feedbackUser: '陈晨',
        handler: '刘工',
        date: '2026-06-17',
        mergeGroup: '',
    },
    {
        id: 'CS-20260616-0004',
        source: '客服沟通',
        createMode: '人工录入',
        brand: '云康宝',
        site: '京东',
        productType: '血压计',
        model: 'BP-02',
        internal: 'YK-BP02-CN',
        asin: '-',
        raw: '用户咨询袖带尺寸是否适合上臂围 42cm，需要客服跟进配件建议。',
        ai: '咨询大臂围用户的袖带适配问题。',
        level1: '咨询服务',
        level2: '配件适配',
        level3: '袖带尺寸',
        sentiment: '中性',
        returned: '否',
        exception: '否',
        processRoute: '已直接回复关闭',
        processState: '已处理',
        feedbackUser: '王雪',
        handler: '王工',
        date: '2026-06-16',
        mergeGroup: '',
    },
    {
        id: 'CM-20260615-0005',
        mergeGroup: 'MG20_NOISE',
        source: '商品评论',
        createMode: 'AI自动创建',
        brand: 'LF',
        site: '抖音',
        productType: '筋膜枪',
        model: 'MG20',
        internal: 'LF-MG20-DY',
        asin: '-',
        raw: '三档运行时噪音明显，夜间使用会影响家人休息。',
        ai: '筋膜枪高档位噪音明显，影响夜间使用体验。',
        level1: '产品体验',
        level2: '功能效果',
        level3: '噪音偏大',
        sentiment: '负向',
        returned: '否',
        exception: 'P3',
        processRoute: '待处理',
        processState: '待处理',
        feedbackUser: '赵敏',
        handler: '孙工',
        date: '2026-06-15',
    },
    {
        id: 'CM-20260615-0006',
        mergeGroup: 'MG20_NOISE',
        source: '客服沟通',
        createMode: '人工录入',
        brand: 'LF',
        site: '京东',
        productType: '筋膜枪',
        model: 'MG20',
        internal: 'LF-MG20-JD',
        asin: '-',
        raw: '用户反馈使用高档位时声音偏尖，询问是否属于正常现象。',
        ai: '高档位声音偏尖，需确认电机和结构噪音表现。',
        level1: '产品体验',
        level2: '功能效果',
        level3: '噪音偏大',
        sentiment: '负向',
        returned: '否',
        exception: 'P3',
        processRoute: '已转异常',
        processState: '已处理',
        feedbackUser: '周杰',
        handler: '孙工',
        date: '2026-06-15',
    },
];

// ========== 工单数据 ==========
export const workOrderData: WorkOrder[] = [
    {
        id: 'TK-20260611-0342',
        summary:
            'CS20A 无法开机问题批量分析——分析用户测量日志，排查电池仓接触设计和PCB电源管理模块',
        relatedFeedback: 'FB-20260611-00122',
        productLine: '八电极产品线',
        status: '处理中',
        owner: '王工',
        dept: '产品部',
        sla: '18h 22m',
        result: '分析测量日志',
        closeReason: '-',
        exception: '否',
        requirement: '预留',
        qa: '否',
        step: 3,
        aiAbstract:
            'CS20A型号自2026年6月起集中收到无法开机反馈，累计已合并2条同类反馈。初步排查指向电池仓弹片接触不良与PCB电源管理模块低温失效。建议：(1) 隔离当前批次电池仓组件，安排供应商复测弹片回弹力；(2) PCB layout增加电源管理模块滤波电容；(3) QA增加-10°C低温开机循环测试。',
        closeNote: '',
    },
    {
        id: 'TK-20260611-0339',
        summary: 'APP版本兼容排查——AF-30B出现数据同步失败，需排查Android 14兼容性',
        relatedFeedback: 'FB-20260611-00121',
        productLine: '体脂秤产品线',
        status: '待确认',
        owner: '刘工',
        dept: '研发部',
        sla: '31h 10m',
        result: 'APP版本兼容排查',
        closeReason: '-',
        exception: '否',
        requirement: '否',
        qa: '否',
        step: 4,
        aiAbstract:
            'AF-30B在Android 14系统上出现BLE连接超时和数据同步失败问题。初步分析指向Android 14新增的蓝牙权限模型变化。建议：(1) 适配Android 14的BLUETOOTH_CONNECT权限；(2) 增加重连重试机制；(3) 发布热修复版本。',
        closeNote: '',
    },
    {
        id: 'TK-20260610-0318',
        summary: '血压计袖带尺寸适配指引——补充大臂围用户的选购建议和配件方案',
        relatedFeedback: 'FB-20260610-00117',
        productLine: '人体秤产品线',
        status: '已闭环',
        owner: '孙工',
        dept: '产品部',
        sla: '完成',
        result: '补充使用指导与Listing说明',
        closeReason: '已回复',
        exception: '否',
        requirement: '预留',
        qa: '否',
        step: 5,
        aiAbstract:
            'BP-02血压计标准袖带适用上臂围22-32cm，多位大臂围用户反馈测量不适。已补充：(1) Listing增加袖带尺寸选择指引；(2) 开发大号袖带可选配件；(3) Q&A增加视频指引。建议后续产品迭代时标配双尺寸袖带。',
        closeNote: '已补充Listing说明，用户已确认满意。',
    },
];

// ========== 异常数据 ==========
export const emergencyData: EmergencyException[] = [
    {
        id: 'P1-20260611-008',
        level: 'P1',
        region: '海外',
        site: 'Amazon',
        productLine: '八电极秤',
        internal: 'GE31002B1-CS',
        creator: '陈晨',
        dimension: '平台合规',
        source: '投诉/舆情',
        deadline: '已超时 2h',
        reminderLimit: '2h',
        reminderDeadline: '2026-06-05 12:00',
        overdue: true,
        owner: '陈总',
        team: '海外运营+产品经理',
        status: '临时方案超时',
        issue: '玻璃碎裂投诉连续上升',
        impactScope: 'GE31002B1-CS 批次 2026Q1，约500台',
        action: '隔离相关批次，检查包装防护',
        feedback: 'CS-20260618-合并（2条数据）',
        tempPlan: '',
        rootCause: '待根因分析',
        fixPlan: '待整改措施',
        verifyResult: '待验证',
        step: 0,
    },
    {
        id: 'P0-20260611-007',
        level: 'P0',
        region: '国内',
        site: '京东',
        productLine: '体脂秤',
        internal: 'FT31002A2',
        creator: '张伟',
        dimension: '客户伤害',
        source: '退货原因',
        deadline: '剩余 1h 30m',
        reminderLimit: '2h',
        reminderDeadline: '2026-06-05 08:45',
        overdue: false,
        owner: '刘海州',
        team: '售后负责人+质量负责人',
        status: '临时方案输出',
        issue: '测脂不准导致退货率升高',
        impactScope: 'FT31002A2 全批次，约2000台',
        action: '暂停相关投放，输出说明书修订',
        feedback: 'CS-20260617-0003',
        tempPlan: '售后先行解释并补发测量指引',
        rootCause: '传感器数据与说明书口径不一致',
        fixPlan: '优化测量引导和算法提示',
        verifyResult: '待验证',
        step: 2,
    },
];

// ========== 竞品数据 ==========
// 对应 gh-pages 完整版 compareProducts 结构
export const competitorData: Competitor[] = [
    {
        id: 'withings',
        category: '八电极秤',
        type: '标杆产品',
        brand: 'Withings',
        name: 'Body Scan',
        model: 'WBS08',
        productType: '八电极体脂秤',
        position: '旗舰',
        launch: '2023-10',
        platform: 'Amazon / 独立站',
        region: '美国 / 欧洲',
        channelType: '海外',
        asin: 'B0CJZ3KN8P',
        price: 349.95,
        officialPrice: '$399.95',
        dealPrice: '$349.95',
        rating: '4.4',
        reviews: '8,920',
        sellingPoints: '分段身体成分 / 心率 / 血管年龄',
        specs: '8电极；Wi-Fi/Bluetooth；12个月续航',
        pain: '价格高，部分用户质疑体脂和水分读数波动。',
        monitorStatus: '正常监控',
        archived: false,
        registerFields: {
            竞品类型: '标杆产品',
            内部竞品: '否',
            品牌: 'Withings',
            产品名称: 'Body Scan',
            产品型号: 'WBS08',
            产品类型: '八电极体脂秤',
            产品定位: '旗舰',
            上市时间: '2023-10',
            销售平台: 'Amazon / 独立站',
            销售区域: '美国 / 欧洲',
            竞品链接: 'https://www.withings.com/body-scan',
            信息来源: '品牌官网 / Amazon详情页',
            信息采集日期: '2026-06-18',
            信息采集人: '产品经理',
            信息状态: '正常监控',
            官方售价: '$399.95',
            到手价: '$349.95',
            币种: 'USD',
            价格区间: '$300-$499',
        },
    },
    {
        id: 'renpho',
        category: '体脂秤',
        type: '直接竞争产品',
        brand: 'RENPHO',
        name: 'Elis 1 Smart Scale',
        model: 'ES-CS20M',
        productType: '四电极体脂秤',
        position: '大众级',
        launch: '2024-03',
        platform: 'Amazon / Walmart',
        region: '美国',
        channelType: '海外',
        asin: 'B08H5N4K9P',
        price: 39.99,
        officialPrice: '$49.99',
        dealPrice: '$39.99',
        rating: '4.6',
        reviews: '23,400',
        sellingPoints: '低价高评价 / App趋势 / 家庭多人',
        specs: '4电极；Bluetooth；AAA电池',
        pain: '低价促销频繁，压缩入门价格带。',
        monitorStatus: '正常监控',
        archived: false,
        registerFields: {
            竞品类型: '直接竞争产品',
            内部竞品: '否',
            品牌: 'RENPHO',
            产品名称: 'Elis 1 Smart Scale',
            产品型号: 'ES-CS20M',
            产品类型: '四电极体脂秤',
            产品定位: '大众级',
            上市时间: '2024-03',
            销售平台: 'Amazon / Walmart',
            销售区域: '美国',
            竞品链接: 'https://www.renpho.com',
            信息来源: 'Amazon详情页 / Walmart详情页',
            信息采集日期: '2026-06-17',
            信息采集人: '产品经理',
            信息状态: '正常监控',
            官方售价: '$49.99',
            到手价: '$39.99',
            币种: 'USD',
            价格区间: '$30-$50',
        },
    },
    {
        id: 'huawei',
        category: '八电极秤',
        type: '直接竞争产品',
        brand: '华为',
        name: '智能体脂秤 3 Pro',
        model: 'Scale 3 Pro',
        productType: '八电极体脂秤',
        position: '中高端',
        launch: '2024-05',
        platform: '天猫 / 京东 / 抖音',
        region: '中国',
        channelType: '国内',
        asin: '--',
        price: 399,
        officialPrice: '¥499',
        dealPrice: '¥399',
        rating: '4.8',
        reviews: '18,260',
        sellingPoints: '华为生态 / 八电极分段测量 / 大促流量强',
        specs: '8电极；HarmonyOS生态；蓝牙连接',
        pain: '生态绑定强，非华为用户体验优势减弱。',
        monitorStatus: '正常监控',
        archived: false,
        registerFields: {
            竞品类型: '直接竞争产品',
            内部竞品: '否',
            品牌: '华为',
            产品名称: '智能体脂秤 3 Pro',
            产品型号: 'Scale 3 Pro',
            产品类型: '八电极体脂秤',
            产品定位: '中高端',
            上市时间: '2024-05',
            销售平台: '天猫 / 京东 / 抖音',
            销售区域: '中国',
            竞品链接: 'https://consumer.huawei.com',
            信息来源: '天猫详情页 / 京东详情页',
            信息采集日期: '2026-06-16',
            信息采集人: '产品经理',
            信息状态: '正常监控',
            官方售价: '¥499',
            到手价: '¥399',
            币种: 'CNY',
            价格区间: '¥300-¥499',
        },
    },
];

// 竞品等级监控记录
export const defaultLevelRecords: LevelRecord[] = [
    {
        level: 'L1',
        source: '日常监控',
        content: '页面卖点与价格无明显变化。',
        action: '继续监控',
        status: '展示',
        date: '2026-06-03',
    },
    {
        level: 'L2',
        source: '价格/排名',
        content: '价格小幅波动，未形成明确业务影响。',
        action: '继续监控',
        status: '展示',
        date: '2026-06-09',
    },
    {
        level: 'L3',
        source: '触发提醒',
        content: '近7天价格、排名或差评趋势变化明显。',
        action: '转入需求',
        status: '已提醒产品经理',
        date: '2026-06-15',
    },
    {
        level: 'L4',
        source: '紧急提醒',
        content: '出现关键功能变化，需要实物分析确认。',
        action: '启动实物分析',
        status: '处理中',
        date: '2026-06-18',
    },
];

// 竞品登记参数字段定义（秤类）
export const competitorScaleFields: CompetitorFieldDef[] = [
    {
        category: '基础信息',
        name: '竞品类型',
        type: 'select',
        required: true,
        options: ['直接竞争产品', '间接竞争产品'],
    },
    {
        category: '基础信息',
        name: '内部竞品',
        type: 'select',
        required: false,
        options: ['否', '是'],
    },
    { category: '基础信息', name: '品牌', type: 'text', required: true, placeholder: 'Withings' },
    {
        category: '基础信息',
        name: '产品名称',
        type: 'text',
        required: true,
        placeholder: 'Body Comp',
    },
    { category: '基础信息', name: '产品型号', type: 'text', required: true, placeholder: 'WBS08' },
    { category: '基础信息', name: '产品类型', type: 'lineSelect', required: true },
    {
        category: '基础信息',
        name: '产品定位',
        type: 'select',
        required: true,
        options: ['入门级', '大众级', '中端', '高端'],
    },
    {
        category: '基础信息',
        name: '上市时间',
        type: 'text',
        required: false,
        placeholder: 'YYYY-MM 或 2023年10月',
    },
    {
        category: '基础信息',
        name: '销售平台',
        type: 'text',
        required: true,
        placeholder: 'Amazon / 天猫 / 京东',
    },
    {
        category: '基础信息',
        name: '销售区域',
        type: 'text',
        required: true,
        placeholder: '中国 / 美国 / 加拿大 / 欧洲',
    },
    {
        category: '基础信息',
        name: '竞品链接',
        type: 'url',
        required: true,
        placeholder: '商品链接或官网链接',
    },
    {
        category: '基础信息',
        name: '信息来源',
        type: 'text',
        required: true,
        placeholder: '平台详情页 / 品牌官网 / 实物样机',
    },
    { category: '基础信息', name: '信息采集日期', type: 'date', required: true },
    {
        category: '基础信息',
        name: '信息采集人',
        type: 'text',
        required: true,
        placeholder: '填写采集人',
    },
    {
        category: '基础信息',
        name: '信息状态',
        type: 'select',
        required: true,
        options: ['正常监控', '待补充', '待校验', '已归档'],
    },
    {
        category: '销售信息',
        name: '官方售价',
        type: 'number',
        required: false,
        placeholder: '399.95',
    },
    { category: '销售信息', name: '到手价', type: 'number', required: true, placeholder: '349.95' },
    {
        category: '销售信息',
        name: '币种',
        type: 'select',
        required: true,
        options: ['USD', 'CNY', 'EUR', 'JPY', 'GBP'],
    },
    {
        category: '销售信息',
        name: '价格区间',
        type: 'text',
        required: false,
        placeholder: '¥299-¥499',
    },
    { category: '外观结构', name: '长度(mm)', type: 'text', required: false, placeholder: '320' },
    { category: '外观结构', name: '宽度(mm)', type: 'text', required: false, placeholder: '320' },
    { category: '外观结构', name: '厚度(mm)', type: 'text', required: false, placeholder: '25' },
    {
        category: '外观结构',
        name: '产品重量(kg)',
        type: 'text',
        required: false,
        placeholder: '2.1',
    },
    {
        category: '外观结构',
        name: '玻璃类型',
        type: 'text',
        required: false,
        placeholder: '钢化玻璃',
    },
    { category: '外观结构', name: '玻璃厚度', type: 'text', required: false, placeholder: '6mm' },
    {
        category: '外观结构',
        name: '底壳结构',
        type: 'text',
        required: false,
        placeholder: '一体式注塑',
    },
    {
        category: '外观结构',
        name: '机身材质',
        type: 'text',
        required: false,
        placeholder: 'ABS+钢化玻璃',
    },
    {
        category: '外观结构',
        name: '表面工艺',
        type: 'text',
        required: false,
        placeholder: '喷涂/IML',
    },
    { category: '外观结构', name: '颜色', type: 'text', required: false, placeholder: '白色' },
    {
        category: '外观结构',
        name: '按键类型',
        type: 'text',
        required: false,
        placeholder: '触摸/物理',
    },
    {
        category: '外观结构',
        name: '防滑脚垫',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '外观结构',
        name: '秤面站位引导',
        type: 'text',
        required: false,
        placeholder: '脚印图标/文字',
    },
    {
        category: '电极系统',
        name: '是否支持测脂',
        type: 'select',
        required: false,
        options: ['是', '否'],
    },
    {
        category: '电极系统',
        name: '电极类型',
        type: 'text',
        required: false,
        placeholder: 'ITO/金属',
    },
    { category: '电极系统', name: '电极数量', type: 'text', required: false, placeholder: '4' },
    { category: '电极系统', name: '脚部电极数量', type: 'text', required: false, placeholder: '2' },
    { category: '电极系统', name: '手部电极数量', type: 'text', required: false, placeholder: '2' },
    {
        category: '电极系统',
        name: '是否有手柄',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '电极系统',
        name: '手柄类型',
        type: 'text',
        required: false,
        placeholder: '可拆卸/固定',
    },
    {
        category: '电极系统',
        name: '手柄连接方式',
        type: 'text',
        required: false,
        placeholder: '线缆/无线',
    },
    { category: '称重系统', name: '起称重量', type: 'text', required: false, placeholder: '5kg' },
    { category: '称重系统', name: '最大称重', type: 'text', required: false, placeholder: '180kg' },
    { category: '称重系统', name: '分度值', type: 'text', required: false, placeholder: '0.1kg' },
    {
        category: '称重系统',
        name: '单位切换',
        type: 'text',
        required: false,
        placeholder: 'kg/lb/st',
    },
    {
        category: '称重系统',
        name: '传感器类型',
        type: 'text',
        required: false,
        placeholder: '四点式称重传感器',
    },
    {
        category: '称重系统',
        name: '称重精度说明',
        type: 'text',
        required: false,
        placeholder: '±0.1kg',
    },
    {
        category: '测量系统',
        name: 'APP测量指标',
        type: 'text',
        required: false,
        placeholder: '体脂率/肌肉量/水分率等',
    },
    {
        category: '测量系统',
        name: '本机测量/显示指标',
        type: 'text',
        required: false,
        placeholder: '体重/体脂率',
    },
    { category: '测量系统', name: '测量频率', type: 'text', required: false, placeholder: '50kHz' },
    {
        category: '测量系统',
        name: '运动员模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '测量系统',
        name: '孕妇模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '测量系统',
        name: '婴儿模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '测量系统',
        name: '访客模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '测量系统',
        name: '宠物/抱婴称重模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '显示系统',
        name: '屏幕类型',
        type: 'text',
        required: false,
        placeholder: 'LCD/LED/彩屏',
    },
    {
        category: '显示系统',
        name: '屏幕尺寸',
        type: 'text',
        required: false,
        placeholder: '3.5英寸',
    },
    {
        category: '显示系统',
        name: '屏幕位置',
        type: 'text',
        required: false,
        placeholder: '顶部居中',
    },
    {
        category: '显示系统',
        name: '屏幕显示语言',
        type: 'text',
        required: false,
        placeholder: '英文',
    },
    {
        category: '显示系统',
        name: '用户识别显示',
        type: 'text',
        required: false,
        placeholder: '姓名/头像/编号',
    },
    {
        category: '显示系统',
        name: '趋势/等级显示',
        type: 'text',
        required: false,
        placeholder: '箭头/颜色分级',
    },
    {
        category: '智能系统',
        name: 'APP连接',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '智能系统',
        name: 'APP名称',
        type: 'text',
        required: false,
        placeholder: 'Withings App',
    },
    {
        category: '智能系统',
        name: '连接方式',
        type: 'text',
        required: false,
        placeholder: 'Wi-Fi/Bluetooth',
    },
    {
        category: '智能系统',
        name: 'OTA升级',
        type: 'select',
        required: false,
        options: ['支持', '不支持'],
    },
    {
        category: '智能系统',
        name: '数据同步/生态接入',
        type: 'text',
        required: false,
        placeholder: 'Apple Health / Google Fit',
    },
    {
        category: '智能系统',
        name: '多用户识别',
        type: 'select',
        required: false,
        options: ['支持', '不支持'],
    },
    {
        category: '智能系统',
        name: '自动用户识别',
        type: 'select',
        required: false,
        options: ['支持', '不支持'],
    },
    {
        category: '智能系统',
        name: '历史数据趋势',
        type: 'select',
        required: false,
        options: ['支持', '不支持'],
    },
    {
        category: '智能系统',
        name: '家庭成员管理',
        type: 'select',
        required: false,
        options: ['支持', '不支持'],
    },
    {
        category: '智能系统',
        name: '数据报告形式',
        type: 'text',
        required: false,
        placeholder: '图表/PDF/周报',
    },
    {
        category: '电源系统',
        name: '供电方式',
        type: 'text',
        required: false,
        placeholder: 'AAA电池/USB充电',
    },
    { category: '电源系统', name: '电池数量', type: 'text', required: false, placeholder: '4节' },
    {
        category: '电源系统',
        name: 'Type-C充电',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '电源系统',
        name: '续航时间',
        type: 'text',
        required: false,
        placeholder: '12个月',
    },
    {
        category: '电源系统',
        name: '低电提示',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '包装配件',
        name: '包装形式',
        type: 'text',
        required: false,
        placeholder: '彩盒/白盒/吸塑',
    },
    {
        category: '包装配件',
        name: '包装语言',
        type: 'text',
        required: false,
        placeholder: '英文/中文',
    },
    {
        category: '包装配件',
        name: '说明书',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    { category: '包装配件', name: '电池', type: 'select', required: false, options: ['有', '无'] },
];

// 竞品登记参数字段定义（筋膜枪）
export const competitorMassageFields: CompetitorFieldDef[] = [
    {
        category: '基础信息',
        name: '竞品类型',
        type: 'select',
        required: true,
        options: ['直接竞争产品', '间接竞争产品'],
    },
    {
        category: '基础信息',
        name: '内部竞品',
        type: 'select',
        required: false,
        options: ['否', '是'],
    },
    { category: '基础信息', name: '品牌', type: 'text', required: true, placeholder: 'Withings' },
    {
        category: '基础信息',
        name: '产品名称',
        type: 'text',
        required: true,
        placeholder: 'Body Comp',
    },
    { category: '基础信息', name: '产品型号', type: 'text', required: true, placeholder: 'WBS08' },
    { category: '基础信息', name: '产品类型', type: 'lineSelect', required: true },
    {
        category: '基础信息',
        name: '产品定位',
        type: 'select',
        required: true,
        options: ['入门级', '大众级', '中端', '高端'],
    },
    {
        category: '基础信息',
        name: '上市时间',
        type: 'text',
        required: false,
        placeholder: 'YYYY-MM 或 2023年10月',
    },
    {
        category: '基础信息',
        name: '销售平台',
        type: 'text',
        required: true,
        placeholder: 'Amazon / 天猫 / 京东',
    },
    {
        category: '基础信息',
        name: '销售区域',
        type: 'text',
        required: true,
        placeholder: '中国 / 美国 / 加拿大 / 欧洲',
    },
    {
        category: '基础信息',
        name: '竞品链接',
        type: 'url',
        required: true,
        placeholder: '商品链接或官网链接',
    },
    {
        category: '基础信息',
        name: '信息来源',
        type: 'text',
        required: true,
        placeholder: '平台详情页 / 品牌官网 / 实物样机',
    },
    { category: '基础信息', name: '信息采集日期', type: 'date', required: true },
    {
        category: '基础信息',
        name: '信息采集人',
        type: 'text',
        required: true,
        placeholder: '填写采集人',
    },
    {
        category: '基础信息',
        name: '信息状态',
        type: 'select',
        required: true,
        options: ['正常监控', '待补充', '待校验', '已归档'],
    },
    {
        category: '销售信息',
        name: '官方售价',
        type: 'number',
        required: false,
        placeholder: '399.95',
    },
    { category: '销售信息', name: '到手价', type: 'number', required: true, placeholder: '349.95' },
    {
        category: '销售信息',
        name: '币种',
        type: 'select',
        required: true,
        options: ['USD', 'CNY', 'EUR', 'JPY', 'GBP'],
    },
    {
        category: '销售信息',
        name: '价格区间',
        type: 'text',
        required: false,
        placeholder: '¥299-¥499',
    },
    { category: '外观结构', name: '长度(mm)', type: 'text', required: false, placeholder: '150' },
    { category: '外观结构', name: '宽度(mm)', type: 'text', required: false, placeholder: '60' },
    {
        category: '外观结构',
        name: '厚度/高度(mm)',
        type: 'text',
        required: false,
        placeholder: '45',
    },
    {
        category: '外观结构',
        name: '产品净重(g)',
        type: 'text',
        required: false,
        placeholder: '350',
    },
    {
        category: '外观结构',
        name: '机身材质',
        type: 'text',
        required: false,
        placeholder: 'ABS+硅胶',
    },
    {
        category: '外观结构',
        name: '表面工艺',
        type: 'text',
        required: false,
        placeholder: '喷涂/包胶',
    },
    { category: '外观结构', name: '颜色', type: 'text', required: false, placeholder: '深空灰' },
    {
        category: '外观结构',
        name: '握持方式',
        type: 'text',
        required: false,
        placeholder: 'T型/枪型/直筒',
    },
    {
        category: '外观结构',
        name: '防滑设计',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '外观结构',
        name: '人体工学设计',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '动力系统',
        name: '电机类型',
        type: 'text',
        required: false,
        placeholder: '无刷电机',
    },
    {
        category: '动力系统',
        name: '振幅/冲程(mm)',
        type: 'text',
        required: false,
        placeholder: '12',
    },
    { category: '动力系统', name: '最大推力', type: 'text', required: false, placeholder: '16kg' },
    {
        category: '动力系统',
        name: '最低转速(rpm)',
        type: 'text',
        required: false,
        placeholder: '1800',
    },
    {
        category: '动力系统',
        name: '最高转速(rpm)',
        type: 'text',
        required: false,
        placeholder: '3200',
    },
    { category: '动力系统', name: '噪音(dB)', type: 'text', required: false, placeholder: '45' },
    { category: '动力系统', name: '档位数量', type: 'text', required: false, placeholder: '5' },
    {
        category: '动力系统',
        name: '力度体验备注',
        type: 'text',
        required: false,
        placeholder: '强劲/柔和/适中',
    },
    {
        category: '电源系统',
        name: '电池容量(mAh)',
        type: 'text',
        required: false,
        placeholder: '2500',
    },
    {
        category: '电源系统',
        name: '电池类型',
        type: 'text',
        required: false,
        placeholder: '18650锂电池',
    },
    {
        category: '电源系统',
        name: '官方续航时间',
        type: 'text',
        required: false,
        placeholder: '6小时',
    },
    {
        category: '电源系统',
        name: '充电接口',
        type: 'text',
        required: false,
        placeholder: 'Type-C',
    },
    {
        category: '电源系统',
        name: '快充功能',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '电源系统',
        name: '低电提示',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    { category: '按摩头系统', name: '按摩头数量', type: 'text', required: false, placeholder: '6' },
    {
        category: '按摩头系统',
        name: '按摩头类型',
        type: 'text',
        required: false,
        placeholder: '球形/锥形/U型/平头',
    },
    {
        category: '按摩头系统',
        name: '按摩头连接方式',
        type: 'text',
        required: false,
        placeholder: '卡扣式/螺纹式',
    },
    {
        category: '按摩头系统',
        name: '按摩头材质',
        type: 'text',
        required: false,
        placeholder: '硅胶/EVA/泡沫',
    },
    {
        category: '功能系统',
        name: '压力感应',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '智能档位',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '档位记忆',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '定时保护',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '自动模式',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '热敷功能',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '功能系统',
        name: '冷敷功能',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '智能系统',
        name: '通信方式',
        type: 'text',
        required: false,
        placeholder: 'Bluetooth',
    },
    {
        category: '智能系统',
        name: 'APP名称',
        type: 'text',
        required: false,
        placeholder: 'Hyperice App',
    },
    {
        category: '智能系统',
        name: 'APP核心功能',
        type: 'text',
        required: false,
        placeholder: '力度调节/教学视频',
    },
    {
        category: '包装配件',
        name: '包装形式',
        type: 'text',
        required: false,
        placeholder: '彩盒/手提箱',
    },
    {
        category: '包装配件',
        name: '包装语言',
        type: 'text',
        required: false,
        placeholder: '英文/中文',
    },
    {
        category: '包装配件',
        name: '收纳包',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '包装配件',
        name: '充电线',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
    {
        category: '包装配件',
        name: '说明书',
        type: 'select',
        required: false,
        options: ['有', '无'],
    },
];

// 产品线对应的参数字段
export const competitorParamFieldsMap: Record<string, CompetitorFieldDef[]> = {
    八电极秤: competitorScaleFields,
    体脂秤: competitorScaleFields,
    筋膜枪: competitorMassageFields,
};

// 产品类型动态选项
export const competitorProductTypeOptions: Record<string, string[]> = {
    八电极秤: ['八电极体脂秤', '四电极体脂秤', '体重秤'],
    体脂秤: ['体脂秤', '体重秤', '智能健康秤'],
    筋膜枪: ['迷你筋膜枪', '专业筋膜枪', '热敷筋膜枪'],
};

// ========== 报告数据 ==========
export const reportData: Report[] = [
    {
        id: 'RPT-001',
        title: '用户反馈周报 (6/16-6/22)',
        period: '2026-06-16 ~ 2026-06-22',
        type: '周报',
        date: '2026-06-23',
        summary: '本周反馈总量上升，退货率略有下降，筋膜枪类噪音问题持续。',
    },
    {
        id: 'RPT-002',
        title: '异常统计分析月报',
        period: '2026年6月',
        type: '月报',
        date: '2026-06-01',
        summary: 'P0/P1异常件数同比持平，玻璃碎裂和测脂不准为高发问题。',
    },
    {
        id: 'RPT-003',
        title: '有效信息转需求清单',
        period: '2026年Q2',
        type: '需求',
        date: '2026-06-15',
        summary: '本季度已转需求线索 12 条，进入规划评审阶段 3 条。',
    },
];

// ========== Q&A数据 ==========
export const knowledgeData: KnowledgeItem[] = [
    {
        id: 'QA-001',
        question: '体脂秤无法开机怎么办？',
        answer: '请检查电池是否装反或电量不足。更换新电池后仍无法开机，请联系售后处理。部分型号需长按电源键 3 秒。',
        category: '产品质量',
        tags: ['无法开机', '电池', '硬件'],
        date: '2026-06-18',
    },
    {
        id: 'QA-002',
        question: 'APP无法同步测量数据？',
        answer: '请确认蓝牙已打开且设备在 1 米范围内。尝试关闭APP后重新打开，或重启手机蓝牙。如仍无法同步，请卸载重装APP。',
        category: '产品体验',
        tags: ['数据同步', 'APP', '蓝牙'],
        date: '2026-06-17',
    },
    {
        id: 'QA-003',
        question: '测脂数据不准确怎么办？',
        answer: '请在硬质平地上测量，双脚与电极片充分接触。测量前避免剧烈运动，保持脚底干燥。不同设备间存在误差，建议以趋势为准。',
        category: '数据准确性',
        tags: ['测脂不准', '使用指引'],
        date: '2026-06-16',
    },
    {
        id: 'QA-004',
        question: '筋膜枪使用时有异响？',
        answer: '低档位噪音正常范围为 40-50dB。如出现金属摩擦声或异常尖鸣，请立即停止使用并联系售后。',
        category: '产品体验',
        tags: ['噪音', '筋膜枪', '异响'],
        date: '2026-06-15',
    },
    {
        id: 'QA-005',
        question: '血压计袖带尺寸如何选择？',
        answer: '标准袖带适用上臂围 22-32cm，大号袖带适用 32-42cm。请根据臂围选择合适尺寸，袖带过小会导致测量值偏高。',
        category: '咨询服务',
        tags: ['袖带', '血压计', '配件'],
        date: '2026-06-14',
    },
];

// ========== 用户角色 ==========
export const userRoleData: UserRole[] = roleOptions;

// ========== 仪表盘 - 过滤栏选项 ==========
export const filterPeriodOptions = ['近7天', '近30天', '近90天', '自定义'];
export const filterBrandOptions = ['全部品牌', '云康宝', 'AF', 'GE', 'LF'];
export const filterSiteOptions = ['全部站点', 'Amazon.com (US)', '天猫', '京东', '抖音'];
export const filterProductTypeOptions = [
    '全部产品类型',
    '体脂秤',
    '人体秤',
    '八电极秤',
    '筋膜枪',
    '按摩产品',
];
export const filterModelOptions = ['全部', 'CS20A', 'CS30B', 'BF511', 'MG20', 'MS30'];
export const filterSourceOptions = [
    '全部',
    '商品评论',
    '退货原因',
    '站内信',
    '客服沟通',
    'APP反馈',
    '社媒',
    'Vine',
    '天使用户',
    '投诉/警告',
];

export const defaultFilters = {
    period: '近30天',
    site: 'Amazon.com (US)',
    brand: '全部品牌',
    productType: '体脂秤',
    model: '全部',
    source: '全部',
};

// ========== 仪表盘 - 指标卡片（含 note1/note2） ==========
export const dashboardMetricCards = [
    {
        label: '退货率',
        value: '4.38%',
        trend: '-0.72%',
        trendType: 'down-good',
        note1: '退货量',
        note2: '1,256',
    },
    {
        label: '反馈率',
        value: '12.67%',
        trend: '-1.34%',
        trendType: 'down-good',
        note1: '反馈量',
        note2: '3,637',
    },
    {
        label: '闭环率',
        value: '87.45%',
        trend: '+3.21%',
        trendType: 'up-good',
        note1: '已闭环',
        note2: '3,178',
    },
    {
        label: '响应达成率',
        value: '92.16%',
        trend: '+4.57%',
        trendType: 'up-good',
        note1: '达成',
        note2: '3,349',
    },
    {
        label: '异常占比',
        value: '6.72%',
        trend: '+0.89%',
        trendType: 'up-bad',
        note1: '异常工单',
        note2: '244',
    },
    {
        label: '差评率',
        value: '3.25%',
        trend: '-0.31%',
        trendType: 'down-good',
        note1: '差评数量',
        note2: '935',
    },
];

export const metricFormulas: Record<string, string> = {
    退货率: '计算公式：退货量/销量',
    反馈率: '计算公式：反馈量/销量',
    闭环率: '计算公式：反馈单据关闭数量/总反馈量（关闭指关闭、转需求、转异常或直接关闭）',
    响应达成率: '计算公式：P0/P1/P2/P3异常在规定时间内响应的达成情况',
    异常占比: '计算公式：产生的异常数量/反馈总数',
    差评率: '计算公式：差评数量/评论总数',
};

// ========== 仪表盘 - 关键指标趋势折线图 ==========
export const trendLineData = [
    {
        label: '闭环率',
        color: '#22a06b',
        values: [82, 84, 83, 85, 86, 86, 87, 88, 87, 89, 88, 90, 91],
        width: 3,
    },
    {
        label: '响应达成率',
        color: '#6d5dfc',
        values: [78, 79, 81, 80, 82, 83, 82, 84, 85, 84, 86, 87, 88],
        width: 3,
    },
    {
        label: '反馈率',
        color: '#ff8a00',
        values: [13.8, 14.1, 13.5, 14.8, 14, 13.6, 13.2, 12.9, 13.4, 12.8, 12.4, 12.1, 11.9],
        width: 2,
    },
    {
        label: '退货率',
        color: '#1f73e8',
        values: [4.9, 5.1, 4.8, 5, 4.7, 4.6, 4.8, 4.5, 4.6, 4.4, 4.5, 4.3, 4.2],
        width: 2,
    },
];
export const trendXLabels = ['03/13', '03/27', '04/10', '04/24', '05/08', '05/22', '06/05'];

// ========== 仪表盘 - 产品型号表现 TOP5 ==========
export const modelTop5Data: [string, number, number, string, string, string, string][] = [
    ['YB-S100 八电极体脂秤', 6528, 856, '4.12%', '13.1%', '4.5分', '3.12%'],
    ['YB-201 人体成分秤', 4932, 642, '4.78%', '13.0%', '4.4分', '3.38%'],
    ['YB-301 体脂秤 Pro', 3765, 487, '4.25%', '12.9%', '4.6分', '3.01%'],
    ['YB-M3 筋膜枪 M3 Pro', 2983, 421, '3.95%', '14.1%', '4.3分', '3.21%'],
    ['YB-F1 智能体脂秤 F1', 2357, 309, '4.88%', '13.1%', '4.2分', '3.45%'],
];

// ========== 仪表盘 - 退货率 vs 反馈率（按产品类型） ==========
export const returnVsFeedbackData: [string, number, number][] = [
    ['体脂秤', 4.38, 12.67],
    ['人体秤', 4.91, 13.24],
    ['八电极秤', 4.12, 13.01],
    ['筋膜枪', 3.28, 14.85],
    ['按摩产品', 4.75, 11.92],
];

// ========== 仪表盘 - 一级反馈分类 ==========
export const level1Categories = [
    { name: '产品质量', value: 36, color: '#1f73e8', mom: 4, yoy: 6 },
    { name: '产品体验', value: 28, color: '#22a06b', mom: -3, yoy: -2 },
    { name: '物流运营', value: 14, color: '#ffb020', mom: -2, yoy: 1 },
    { name: '平台合规', value: 9, color: '#8b5cf6', mom: 2, yoy: 3 },
    { name: '咨询服务', value: 8, color: '#06b6d4', mom: 1, yoy: -1 },
    { name: '其他', value: 5, color: '#94a3b8', mom: -2, yoy: -7 },
];

// ========== 仪表盘 - 二级反馈分类 ==========
export const level2Categories = [
    { name: '硬件问题', value: 24, color: '#1f73e8', mom: 3, yoy: 5 },
    { name: '数据准确性', value: 20, color: '#22a06b', mom: 4, yoy: 6 },
    { name: 'APP问题', value: 16, color: '#ffb020', mom: -1, yoy: 2 },
    { name: '包装配件', value: 13, color: '#8b5cf6', mom: -3, yoy: -1 },
    { name: '功能效果', value: 11, color: '#06b6d4', mom: 2, yoy: 3 },
    { name: '其他', value: 16, color: '#94a3b8', mom: -5, yoy: -15 },
];

// ========== 仪表盘 - 三级反馈分类 ==========
export const level3Categories = [
    { name: '测脂不准', value: 28, color: '#1f73e8', mom: 5, yoy: 7 },
    { name: 'APP连接问题', value: 19, color: '#22a06b', mom: 3, yoy: 5 },
    { name: '功能需求/改进建议', value: 16, color: '#ffb020', mom: -2, yoy: 3 },
    { name: '包装/配件问题', value: 9, color: '#8b5cf6', mom: -2, yoy: 1 },
    { name: '说明书/标识问题', value: 6, color: '#06b6d4', mom: 1, yoy: -1 },
    { name: '其他问题', value: 4, color: '#94a3b8', mom: 0, yoy: -2 },
];

// ========== 仪表盘 - 前5大三级反馈比例对比 ==========
export const top5ComparisonData: [string, number, number, number][] = [
    ['测脂不准', 28, 23, 21],
    ['APP连接问题', 19, 16, 14],
    ['功能需求/改进建议', 16, 18, 13],
    ['包装/配件问题', 9, 11, 8],
    ['说明书/标识问题', 6, 5, 7],
];
export const comparisonLegend = [
    { label: '本期', color: '#1f73e8' },
    { label: '上期', color: '#ff8a00' },
    { label: '去年同期', color: '#22a06b' },
];

// ========== 仪表盘 - 紧急异常动态 ==========
export const emergencyTimelineData = [
    {
        id: 'EX-20260611-008',
        p: 'P1',
        dimension: '平台合规',
        source: '投诉/警告',
        response: '2小时响应 / 24小时方案',
        owner: '运营负责人 + 产品经理',
        status: '处置方案',
        issue: '玻璃碎裂投诉连续上升',
        action: '隔离相关批次，检查包装防护',
        time: '10:15',
    },
    {
        id: 'EX-20260611-007',
        p: 'P2',
        dimension: '客户伤害',
        source: '退货原因',
        response: '6小时响应 / 72小时方案',
        owner: '团队主管 + 售后负责人',
        status: '执行跟进',
        issue: '测脂不准导致退货率升高',
        action: '分析传感器数据与说明书误导',
        time: '09:42',
    },
    {
        id: 'EX-20260610-004',
        p: 'P3',
        dimension: '运营优化',
        source: 'APP反馈',
        response: '24小时响应 / 常规处理',
        owner: '客服专员',
        status: '案例归档',
        issue: '单位切换咨询高频',
        action: 'Q&A新增视频指引',
        time: '08:30',
    },
];
export const emergencyStatusTags = ['新增', '已响应', '处理中'];

// ========== 仪表盘 - TOP质量问题 ==========
export const topQualityIssues: [string, number, string, string, string, string, string][] = [
    ['测脂不准', 8, '23.6%', '+5.2pp', 'CS20A, CS30B', '李工', '72%'],
    ['APP连接问题', 6, '18.9%', '+3.1pp', 'CS20A, CS10M', '王工', '86%'],
    ['无法开机', 5, '12.7%', '-2.7pp', 'CS30B, BF511', '张工', '88%'],
    ['充电问题', 4, '9.4%', '-1.3pp', 'CS20A, CS10M', '赵工', '80%'],
    ['蓝牙断连/不稳定', 5, '8.8%', '-1.6pp', 'CS20A, CS30B', '刘工', '92%'],
];

// ========== 仪表盘 - 质量改善动作看板 ==========
export const qualityBoardSummary = { tasks: 12, closed: 5, overdue: 3 };
export const qualityBoardActions: [string, string, string, number, string][] = [
    ['测脂不准专项', 'CS20A/CS30B', '进行中', 72, '#1f73e8'],
    ['APP连接稳定性', 'CS10/CS20A', '验证中', 86, '#22a06b'],
    ['包装防护整改', 'CS30B', '待验证', 64, '#ff8a00'],
];

// ========== 候选线索数据 ==========
export const candidateLeadData: CandidateLead[] = [
    {
        id: 'REQ-CAND-001',
        sourceFeedback: 'FB-20260611-00122 / FB-20260611-00123',
        category: '产品体验 / 数据准确性',
        title: '体脂秤体成分测量稳定性线索',
        evidence: '同类退货和商品评论集中反馈测脂不准、无法稳定输出体成分。',
        product: '体脂秤 CS20A/CS30B',
        status: '待补充',
        nextAction: '合并同类反馈，补充退货率和差评样本后转产品需求。',
    },
    {
        id: 'REQ-CAND-002',
        sourceFeedback: 'FB-20260611-00121',
        category: '产品体验 / APP问题',
        title: 'Android 14 BLE连接超时线索',
        evidence: 'Android 14 用户集中反馈蓝牙连接超时和数据同步失败。',
        product: '体脂秤 AF-30B',
        status: '待评分',
        nextAction: '补齐Android 14兼容性测试数据后进入五维评分。',
    },
    {
        id: 'REQ-CAND-003',
        sourceFeedback: 'FB-20260610-00117',
        category: '咨询服务 / 配件适配',
        title: '血压计大号袖带配件需求线索',
        evidence: '多位大臂围用户反馈标准袖带不适用，需开发大号袖带配件。',
        product: '血压计 BP-02',
        status: '待补充',
        nextAction: '收集大臂围用户数量和客诉数据，评估配件开发可行性。',
    },
];

// ========== 产品需求池数据 ==========
export const requirementPoolData: RequirementPoolItem[] = [
    {
        id: 'REQ-20260611-001',
        candidate: 'REQ-CAND-001',
        title: '体脂秤体成分测量稳定性优化',
        source: '用户反馈 / 商品评论',
        evidence: '近6个月累计89条测脂不准相关退货/差评反馈，退货率达4.2%。',
        product: '体脂秤 CS20A/CS30B',
        scores: {
            userValue: 5,
            businessImpact: 4,
            feasibility: 3,
            competitiveImpact: 4,
            inventoryImpact: 2,
        },
        level: 'L1',
        path: '紧急修复',
        status: '待审批',
        owner: '李工',
        due: '2026-07-15',
        description:
            '针对CS20A/CS30B体脂秤测量稳定性问题进行系统性优化，包括传感器校准算法升级和测量引导改进。',
        painPoint:
            '用户购买体脂秤的核心诉求是获得准确的体成分数据。测脂不准直接动摇产品价值基础，导致退货率居高不下。',
        expectedValue: '预计降低测脂相关退货率1.5pp，用户满意度提升至4.5分以上。',
        risk: '算法升级可能影响现有用户数据一致性，需要充分测试和灰度发布策略。',
        nextAction: '产品经理评审通过后进入技术评审和排期。',
        relatedFeedback: 'FB-20260611-00122 / FB-20260611-00123',
    },
    {
        id: 'REQ-20260611-002',
        candidate: 'REQ-CAND-002',
        title: 'APP Android 14 BLE兼容性适配',
        source: 'APP反馈 / Google Play评论',
        evidence: 'Android 14更新后，AF-30B蓝牙连接成功率下降23%。',
        product: '体脂秤 AF-30B',
        scores: {
            userValue: 4,
            businessImpact: 3,
            feasibility: 5,
            competitiveImpact: 2,
            inventoryImpact: 1,
        },
        level: 'L3',
        path: '功能升级',
        status: '评分确认',
        owner: '王工',
        due: '2026-08-01',
        description: '适配Android 14新增的蓝牙权限模型，增加重连重试机制，发布热修复版本。',
        painPoint: 'Android 14用户无法正常使用产品，影响新用户首单体验和留存。',
        expectedValue: '恢复Android 14用户正常使用，连接成功率恢复至95%以上。',
        risk: 'Android版本碎片化可能导致部分定制ROM兼容性问题。',
        nextAction: '确认五维评分后进入版本规划。',
        relatedFeedback: 'FB-20260611-00121',
    },
    {
        id: 'REQ-20260610-006',
        candidate: 'REQ-CAND-003',
        title: '血压计大号袖带配件开发',
        source: '客服沟通 / 退货原因',
        evidence: '近3个月大臂围用户（>32cm）客诉量18件，其中5件退货。',
        product: '血压计 BP-02',
        scores: {
            userValue: 3,
            businessImpact: 3,
            feasibility: 4,
            competitiveImpact: 3,
            inventoryImpact: 2,
        },
        level: 'L2',
        path: '体验优化',
        status: '已入池',
        owner: '孙工',
        due: '2026-09-01',
        description: '开发兼容22-42cm臂围的大号袖带配件，并在Listing增加尺寸选择指引。',
        painPoint: '大臂围用户无法使用标准袖带，直接导致购买后无法测量的负面体验。',
        expectedValue: '覆盖大臂围用户群体，预计减少相关退货50%。',
        risk: '配件库存管理需要与标准版区分，增加SKU管理复杂度。',
        nextAction: '进入配件供应商选型和成本评估。',
        relatedFeedback: 'FB-20260610-00117',
    },
    {
        id: 'REQ-20260609-004',
        candidate: 'OBS-20260609-011',
        title: '体脂秤AI健康报告功能',
        source: '竞品分析 / 行业趋势',
        evidence: 'Withings+和Fitbit均已推出AI驱动的个性化健康报告功能。',
        product: '体脂秤 CS20A',
        scores: {
            userValue: 4,
            businessImpact: 4,
            feasibility: 2,
            competitiveImpact: 5,
            inventoryImpact: 1,
        },
        level: 'L4',
        path: '换代开发观察',
        status: '观察池',
        owner: '李工',
        due: '2027-Q1',
        description:
            '基于用户长期测量数据，利用AI生成个性化健康趋势报告和建议，提升用户粘性和品牌价值。',
        painPoint: '当前App仅展示单次测量数据，缺乏长期趋势分析和健康建议，用户使用频次下降明显。',
        expectedValue: '预期提升DAU 30%，用户续费率提升15%。',
        risk: 'AI模型训练需要大量标注数据，且涉及医疗健康合规审查。',
        nextAction: '进入产品规划观察池，持续跟踪竞品动态和用户需求。',
        relatedFeedback: '',
    },
];
