import type {
  FeedbackItem,
  TicketItem,
  ExceptionItem,
  CandidateLead,
  ProductRequirement,
  CompetitorProduct,
  MarketMonitorItem,
  SentimentItem,
  DashboardMetrics,
} from '@/types/feedback';

export const mockFeedbackItems: FeedbackItem[] = [
  {
    id: 'FB-2026-0001',
    title: '美国站体脂秤搜索结果排序异常',
    source: '商品评论',
    site: 'Amazon.com (US)',
    brand: '云康宝',
    productType: '体脂秤',
    salesModel: 'CS20A',
    internalModel: 'YCB-CS20A',
    asin: 'B0XXXXXXX1',
    originalSummary: 'The scale shows inconsistent body fat readings compared to DEXA scan. Multiple users reported same issue.',
    aiSummary: '多名用户反馈体脂读数不一致，与DEXA扫描对比偏差较大',
    categoryL1: '算法',
    categoryL2: '体脂算法',
    categoryL3: '多频测量偏差',
    sentiment: '负面',
    isReturn: '否',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '运营组',
    createdAt: '2026-06-20',
    priority: 'P1',
    status: 'pending',
    summary: '美国站体脂秤CS20A型号搜索结果排序异常，多名用户反馈同一关键词下新品曝光异常',
    tags: ['搜索', '曝光', '美国站'],
  },
  {
    id: 'FB-2026-0002',
    title: '国内电商售后重复建单',
    source: '客服沟通',
    site: '天猫',
    brand: '云康宝',
    productType: '体脂秤',
    salesModel: 'CS30B',
    internalModel: 'YCB-CS30B',
    asin: '',
    originalSummary: '用户通过多个入口提交了相同售后需求，系统生成了3个重复工单',
    aiSummary: '同一用户在多入口提交售后反馈生成重复工单，需增加合并识别规则',
    categoryL1: '功能',
    categoryL2: '售后流程',
    categoryL3: '工单去重',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P2建议',
    disposition: '待分流',
    owner: '客服组',
    createdAt: '2026-06-19',
    priority: 'P2',
    status: 'processing',
    summary: '同一用户多入口提交售后反馈后生成重复工单，需要增加合并识别规则',
    tags: ['售后', '工单', '去重'],
  },
  {
    id: 'FB-2026-0003',
    title: '竞品价格监控触发频率过高',
    source: 'APP反馈',
    site: 'Amazon.com (US)',
    brand: 'AF',
    productType: '筋膜枪',
    salesModel: 'MG20',
    internalModel: 'AF-MG20',
    asin: 'B0XXXXXXX3',
    originalSummary: 'Price monitoring alerts trigger too frequently for minor fluctuations under 5%.',
    aiSummary: '已调整监控阈值和通知频率，避免低价值价格波动持续进入需求池',
    categoryL1: '竞品',
    categoryL2: '价格监控',
    categoryL3: '阈值设置',
    sentiment: '中性',
    isReturn: '否',
    anomalyLevel: '无',
    disposition: '待分流',
    owner: '产品组',
    createdAt: '2026-06-18',
    priority: 'P3',
    status: 'resolved',
    summary: '已调整监控阈值和通知频率，避免低价值价格波动持续进入需求池',
    tags: ['竞品', '监控', '通知'],
  },
  {
    id: 'FB-2026-0004',
    title: '退货率上升-人体秤测量精度投诉',
    source: '退货原因',
    site: 'Amazon.com (US)',
    brand: 'GE',
    productType: '人体秤',
    salesModel: 'BF511',
    internalModel: 'GE-BF511',
    asin: 'B0XXXXXXX4',
    originalSummary: 'Weight readings fluctuate between measurements by 1-2 lbs. Customers returning due to accuracy concerns.',
    aiSummary: '体重读数在不同测量间波动1-2磅，客户因精度问题退货',
    categoryL1: '硬件',
    categoryL2: '传感器',
    categoryL3: '精度漂移',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '品质组',
    createdAt: '2026-06-17',
    priority: 'P1',
    status: 'pending',
    summary: 'GE人体秤测量精度投诉导致退货率上升，传感器精度漂移问题',
    tags: ['退货', '精度', '传感器'],
  },
  {
    id: 'FB-2026-0005',
    title: '社媒投诉-筋膜枪噪音过大',
    source: '社媒',
    site: 'Amazon.com (US)',
    brand: 'AF',
    productType: '筋膜枪',
    salesModel: 'MG20',
    internalModel: 'AF-MG20',
    asin: 'B0XXXXXXX5',
    originalSummary: 'Loud motor noise makes it unusable in quiet environments. Several TikTok videos highlighting this issue.',
    aiSummary: '电机噪音过大不适合安静环境使用，TikTok多段视频指出此问题',
    categoryL1: '硬件',
    categoryL2: '电机',
    categoryL3: '噪音控制',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P2建议',
    disposition: '待分流',
    owner: '产品组',
    createdAt: '2026-06-16',
    priority: 'P2',
    status: 'pending',
    summary: '社媒大量投诉筋膜枪电机噪音问题，需要评估降噪方案',
    tags: ['噪音', '社媒', '筋膜枪'],
  },
  {
    id: 'FB-2026-0006',
    title: 'APP反馈-蓝牙连接不稳定',
    source: 'APP反馈',
    site: 'Amazon.com (US)',
    brand: '云康宝',
    productType: '八电极秤',
    salesModel: 'CS30B',
    internalModel: 'YCB-CS30B',
    asin: 'B0XXXXXXX6',
    originalSummary: 'App frequently disconnects during measurement. Need to restart app to reconnect.',
    aiSummary: 'APP测量过程中频繁断连，需要重启APP才能重连',
    categoryL1: '功能',
    categoryL2: '连接',
    categoryL3: '蓝牙稳定性',
    sentiment: '负面',
    isReturn: '否',
    anomalyLevel: 'P2建议',
    disposition: '待分流',
    owner: '研发组',
    createdAt: '2026-06-15',
    priority: 'P2',
    status: 'processing',
    summary: '八电极秤蓝牙连接频繁断连，需要优化重连机制',
    tags: ['蓝牙', '连接', 'APP'],
  },
  {
    id: 'FB-2026-0007',
    title: 'Vine评论-按摩产品效果不明显',
    source: 'Vine',
    site: 'Amazon.com (US)',
    brand: '云康宝',
    productType: '按摩产品',
    salesModel: 'MS30',
    internalModel: 'YCB-MS30',
    asin: 'B0XXXXXXX7',
    originalSummary: 'Used for 2 weeks, not feeling significant relief. Heat function is the only useful feature.',
    aiSummary: '使用2周效果不明显，仅加热功能有实际用途',
    categoryL1: '功能',
    categoryL2: '按摩效果',
    categoryL3: '力度不足',
    sentiment: '中性',
    isReturn: '是',
    anomalyLevel: 'P3建议',
    disposition: '待分流',
    owner: '产品组',
    createdAt: '2026-06-14',
    priority: 'P3',
    status: 'pending',
    summary: 'Vine评论反馈按摩产品效果不明显，仅加热功能有用',
    tags: ['Vine', '按摩', '效果'],
  },
  {
    id: 'FB-2026-0008',
    title: '站内信投诉-包装破损导致退货',
    source: '站内信',
    site: 'Amazon.com (US)',
    brand: 'LF',
    productType: '体脂秤',
    salesModel: 'CS20A',
    internalModel: 'LF-CS20A',
    asin: 'B0XXXXXXX8',
    originalSummary: 'Product arrived with damaged packaging and scratches on the glass surface. Requesting replacement.',
    aiSummary: '产品到货时包装破损，玻璃表面有划痕，要求换货',
    categoryL1: '品质',
    categoryL2: '包装',
    categoryL3: '运输破损',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '供应链组',
    createdAt: '2026-06-13',
    priority: 'P1',
    status: 'processing',
    summary: 'LF品牌体脂秤运输包装破损频发，玻璃表面划痕引发退货',
    tags: ['包装', '运输', '退货'],
  },
  {
    id: 'FB-2026-0009',
    title: '天使用户反馈-APP体重记录导出问题',
    source: '天使用户',
    site: 'Amazon.com (US)',
    brand: '云康宝',
    productType: '体脂秤',
    salesModel: 'CS20A',
    internalModel: 'YCB-CS20A',
    asin: 'B0XXXXXXX9',
    originalSummary: 'Cannot export historical weight data to CSV. Would be very useful for tracking progress.',
    aiSummary: '无法导出历史体重数据为CSV，用户需要追踪进展',
    categoryL1: '功能',
    categoryL2: '数据管理',
    categoryL3: '导出功能缺失',
    sentiment: '中性',
    isReturn: '否',
    anomalyLevel: '无',
    disposition: '待分流',
    owner: '产品组',
    createdAt: '2026-06-12',
    priority: 'P3',
    status: 'pending',
    summary: '天使用户希望增加历史数据CSV导出功能',
    tags: ['导出', '数据', '天使用户'],
  },
  {
    id: 'FB-2026-0010',
    title: '京东评论-八电极秤APP适配问题',
    source: '商品评论',
    site: '京东',
    brand: '云康宝',
    productType: '八电极秤',
    salesModel: 'CS30B',
    internalModel: 'YCB-CS30B',
    asin: '',
    originalSummary: '华为手机无法安装最新版本APP，希望尽快适配',
    aiSummary: '华为手机无法安装最新版APP，需适配鸿蒙系统',
    categoryL1: '功能',
    categoryL2: '兼容性',
    categoryL3: '系统适配',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P2建议',
    disposition: '待分流',
    owner: '研发组',
    createdAt: '2026-06-11',
    priority: 'P2',
    status: 'pending',
    summary: '京东用户反馈八电极秤APP未适配华为鸿蒙系统',
    tags: ['鸿蒙', '适配', 'APP'],
  },
  {
    id: 'FB-2026-0011',
    title: '抖音反馈-筋膜枪发热异常',
    source: '社媒',
    site: '抖音',
    brand: 'AF',
    productType: '筋膜枪',
    salesModel: 'MG20',
    internalModel: 'AF-MG20',
    asin: '',
    originalSummary: '使用10分钟后电机非常烫手，担心安全问题',
    aiSummary: '使用10分钟后电机过热，存在安全隐患担忧',
    categoryL1: '硬件',
    categoryL2: '电机',
    categoryL3: '过热',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '品质组',
    createdAt: '2026-06-10',
    priority: 'P1',
    status: 'pending',
    summary: '抖音用户反馈筋膜枪使用10分钟电机过热，存在安全风险',
    tags: ['过热', '安全', '抖音'],
  },
  {
    id: 'FB-2026-0012',
    title: '退货原因分析-按摩产品退货率上升',
    source: '退货原因',
    site: 'Amazon.com (US)',
    brand: '云康宝',
    productType: '按摩产品',
    salesModel: 'MS30',
    internalModel: 'YCB-MS30',
    asin: 'B0XXXXXXX7',
    originalSummary: 'Increasing return rate for massage products. Top reasons: weak massage, short battery life, no remote.',
    aiSummary: '按摩产品退货率上升，主因：按摩力度弱、电池续航短、无遥控器',
    categoryL1: '功能',
    categoryL2: '用户体验',
    categoryL3: '续航不足',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P2建议',
    disposition: '待分流',
    owner: '产品组',
    createdAt: '2026-06-09',
    priority: 'P2',
    status: 'pending',
    summary: '按摩产品退货率上升趋势分析：力度弱+续航短+无遥控器',
    tags: ['退货', '电池', '按摩'],
  },
  {
    id: 'FB-2026-0013',
    title: '商品评论-体脂秤APP数据不准确',
    source: '商品评论',
    site: 'Amazon.com (US)',
    brand: 'GE',
    productType: '体脂秤',
    salesModel: 'BF511',
    internalModel: 'GE-BF511',
    asin: 'B0XXXXXXX4',
    originalSummary: 'Body fat percentage jumps 5% between consecutive measurements. Clearly not accurate.',
    aiSummary: '体脂率在连续测量间波动5%，数据明显不准确',
    categoryL1: '算法',
    categoryL2: '体脂算法',
    categoryL3: '数值波动',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '研发组',
    createdAt: '2026-06-08',
    priority: 'P1',
    status: 'pending',
    summary: 'GE体脂秤算法问题导致连续测量体脂率波动5%',
    tags: ['算法', '体脂', '准确度'],
  },
  {
    id: 'FB-2026-0014',
    title: '投诉/警告-Amazon合规问题',
    source: '投诉/警告',
    site: 'Amazon.com (US)',
    brand: 'LF',
    productType: '体脂秤',
    salesModel: 'CS20A',
    internalModel: 'LF-CS20A',
    asin: 'B0XXXXXXX8',
    originalSummary: 'Amazon flagged listing for inaccurate product claims about measurement accuracy.',
    aiSummary: 'Amazon标记产品页面因测量精度声明不准确，存在合规风险',
    categoryL1: '合规',
    categoryL2: '产品声明',
    categoryL3: '精度声明',
    sentiment: '负面',
    isReturn: '否',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '合规组',
    createdAt: '2026-06-07',
    priority: 'P1',
    status: 'processing',
    summary: 'Amazon合规警告：LF体脂秤产品页面精度声明不准确',
    tags: ['合规', 'Amazon', '精度'],
  },
  {
    id: 'FB-2026-0015',
    title: '客服沟通-批量退货人体秤',
    source: '客服沟通',
    site: '天猫',
    brand: '云康宝',
    productType: '人体秤',
    salesModel: 'BF511',
    internalModel: 'YCB-BF511',
    asin: '',
    originalSummary: '客服近期收到大量人体秤退货请求，集中在电池仓生锈和屏幕显示问题',
    aiSummary: '批量退货集中在电池仓生锈和屏幕显示问题',
    categoryL1: '硬件',
    categoryL2: '结构',
    categoryL3: '电池仓腐蚀',
    sentiment: '负面',
    isReturn: '是',
    anomalyLevel: 'P1建议',
    disposition: '待分流',
    owner: '品质组',
    createdAt: '2026-06-06',
    priority: 'P1',
    status: 'processing',
    summary: '天猫批量退货：人体秤电池仓生锈+屏幕显示异常',
    tags: ['批量', '退货', '品质'],
  },
];

export const mockTickets: TicketItem[] = [
  {
    id: 'TK-001',
    title: '调查CS20A体脂读数偏差根因',
    sourceFeedbackId: 'FB-2026-0001',
    status: '处理中',
    priority: 'P1',
    assignee: '研发组-王工',
    createdAt: '2026-06-21',
    deadline: '2026-06-28',
    category: '算法优化',
  },
  {
    id: 'TK-002',
    title: '修复售后重复建单规则',
    sourceFeedbackId: 'FB-2026-0002',
    status: '待处理',
    priority: 'P2',
    assignee: '客服组-李经理',
    createdAt: '2026-06-20',
    deadline: '2026-06-25',
    category: '流程优化',
  },
  {
    id: 'TK-003',
    title: 'GE人体秤传感器精度校准',
    sourceFeedbackId: 'FB-2026-0004',
    status: '处理中',
    priority: 'P1',
    assignee: '品质组-张工',
    createdAt: '2026-06-18',
    deadline: '2026-06-30',
    category: '硬件改进',
  },
  {
    id: 'TK-004',
    title: '优化蓝牙重连机制',
    sourceFeedbackId: 'FB-2026-0006',
    status: '处理中',
    priority: 'P2',
    assignee: '研发组-赵工',
    createdAt: '2026-06-16',
    deadline: '2026-06-24',
    category: '固件升级',
  },
  {
    id: 'TK-005',
    title: 'LF包装防护方案升级',
    sourceFeedbackId: 'FB-2026-0008',
    status: '待确认',
    priority: 'P1',
    assignee: '供应链组-陈经理',
    createdAt: '2026-06-14',
    deadline: '2026-06-22',
    category: '包装改进',
  },
  {
    id: 'TK-006',
    title: '筋膜枪电机散热方案评估',
    sourceFeedbackId: 'FB-2026-0011',
    status: '待处理',
    priority: 'P1',
    assignee: '品质组-刘工',
    createdAt: '2026-06-11',
    deadline: '2026-07-02',
    category: '安全整改',
  },
];

export const mockExceptions: ExceptionItem[] = [
  {
    id: 'EX-001',
    title: 'LF体脂秤精度声明合规风险',
    sourceFeedbackId: 'FB-2026-0014',
    level: 'P1',
    status: '处理中',
    assignee: '合规组-周经理',
    createdAt: '2026-06-07',
    deadline: '2026-06-15',
    impact: 'Listing面临下架风险',
    rootCause: '产品页面精度声称无测试报告支撑',
  },
  {
    id: 'EX-002',
    title: '人体秤批量退货-电池仓腐蚀',
    sourceFeedbackId: 'FB-2026-0015',
    level: 'P1',
    status: '已升级',
    assignee: '品质组-李总监',
    createdAt: '2026-06-06',
    deadline: '2026-06-20',
    impact: '退货率上升2.3%，影响BSR排名',
    rootCause: '电池仓密封等级不足',
  },
  {
    id: 'EX-003',
    title: '筋膜枪电机过热安全风险',
    sourceFeedbackId: 'FB-2026-0011',
    level: 'P0',
    status: '待响应',
    assignee: '产品组-陈总监',
    createdAt: '2026-06-10',
    deadline: '2026-06-13',
    impact: '存在烫伤风险，可能触发产品召回',
    rootCause: '待调查',
  },
];

export const mockCandidateLeads: CandidateLead[] = [
  {
    id: 'CL-001',
    sourceFeedbackId: 'FB-2026-0001',
    category: '算法优化',
    title: '体脂秤多频测量算法校准优化',
    evidenceSummary: '多名美国站用户反馈体脂读数偏差，影响产品信誉和退货率',
    applicableProduct: 'CS20A、CS30B',
    status: '已评分',
  },
  {
    id: 'CL-002',
    sourceFeedbackId: 'FB-2026-0006',
    category: '功能完善',
    title: '蓝牙连接稳定性优化与自动重连',
    evidenceSummary: 'APP反馈大量蓝牙断连问题，影响产品核心体验',
    applicableProduct: 'CS30B',
    status: '待处理',
  },
  {
    id: 'CL-003',
    sourceFeedbackId: 'FB-2026-0013',
    category: '算法优化',
    title: '体脂率测量一致性优化',
    evidenceSummary: 'GE体脂秤连续测量波动5%，需要算法校准',
    applicableProduct: 'BF511',
    status: '补证据',
  },
  {
    id: 'CL-004',
    sourceFeedbackId: 'FB-2026-0005',
    category: '硬件改进',
    title: '筋膜枪静音电机方案',
    evidenceSummary: '社媒大量投诉噪音问题，影响品牌形象',
    applicableProduct: 'MG20',
    status: '已合并',
  },
  {
    id: 'CL-005',
    sourceFeedbackId: 'FB-2026-0010',
    category: '兼容性',
    title: '八电极秤APP鸿蒙系统适配',
    evidenceSummary: '京东用户无法在华为手机使用APP，影响中国市场份额',
    applicableProduct: 'CS30B',
    status: '待处理',
  },
];

export const mockRequirements: ProductRequirement[] = [
  {
    id: 'REQ-001',
    title: '体脂算法多频校准引擎V2.0',
    level: 'L2',
    source: 'FB-2026-0001',
    businessValue: 85,
    userImpact: 90,
    feasibility: 70,
    urgency: 80,
    strategicFit: 75,
    totalScore: 80,
    status: '已通过',
    owner: '产品组',
    createdAt: '2026-06-21',
    tags: ['算法', '体脂', '核心体验'],
  },
  {
    id: 'REQ-002',
    title: '售后工单智能去重系统',
    level: 'L3',
    source: 'FB-2026-0002',
    businessValue: 70,
    userImpact: 65,
    feasibility: 85,
    urgency: 60,
    strategicFit: 55,
    totalScore: 67,
    status: '待评审',
    owner: '客服组',
    createdAt: '2026-06-20',
    tags: ['售后', '去重', '效率'],
  },
  {
    id: 'REQ-003',
    title: '筋膜枪静音电机+散热一体化方案',
    level: 'L1',
    source: 'FB-2026-0005,FB-2026-0011',
    businessValue: 95,
    userImpact: 95,
    feasibility: 65,
    urgency: 95,
    strategicFit: 90,
    totalScore: 88,
    status: '评审中',
    owner: '产品组',
    createdAt: '2026-06-19',
    tags: ['噪音', '安全', '史诗级需求'],
  },
  {
    id: 'REQ-004',
    title: '蓝牙连接稳定性与自动重连方案',
    level: 'L3',
    source: 'FB-2026-0006',
    businessValue: 75,
    userImpact: 80,
    feasibility: 75,
    urgency: 70,
    strategicFit: 60,
    totalScore: 72,
    status: '已通过',
    owner: '研发组',
    createdAt: '2026-06-18',
    tags: ['蓝牙', '连接', '用户体验'],
  },
  {
    id: 'REQ-005',
    title: '产品包装防护升级方案',
    level: 'L2',
    source: 'FB-2026-0008',
    businessValue: 80,
    userImpact: 70,
    feasibility: 90,
    urgency: 75,
    strategicFit: 70,
    totalScore: 77,
    status: '已通过',
    owner: '供应链组',
    createdAt: '2026-06-17',
    tags: ['包装', '运输', '品质'],
  },
  {
    id: 'REQ-006',
    title: '鸿蒙系统APP适配',
    level: 'L2',
    source: 'FB-2026-0010',
    businessValue: 85,
    userImpact: 75,
    feasibility: 60,
    urgency: 80,
    strategicFit: 85,
    totalScore: 77,
    status: '待评审',
    owner: '研发组',
    createdAt: '2026-06-16',
    tags: ['鸿蒙', '适配', '中国市场'],
  },
  {
    id: 'REQ-007',
    title: '用户数据CSV导出功能',
    level: 'L4',
    source: 'FB-2026-0009',
    businessValue: 55,
    userImpact: 60,
    feasibility: 95,
    urgency: 40,
    strategicFit: 50,
    totalScore: 60,
    status: '待评审',
    owner: '产品组',
    createdAt: '2026-06-15',
    tags: ['数据', '导出', '小需求'],
  },
  {
    id: 'REQ-008',
    title: 'GE体脂秤传感器精度升级',
    level: 'L2',
    source: 'FB-2026-0004,FB-2026-0013',
    businessValue: 80,
    userImpact: 85,
    feasibility: 55,
    urgency: 80,
    strategicFit: 75,
    totalScore: 75,
    status: '评审中',
    owner: '品质组',
    createdAt: '2026-06-14',
    tags: ['传感器', '精度', '硬件'],
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  returnRate: 3.8,
  feedbackRate: 12.5,
  closeRate: 78.2,
  responseRate: 92.1,
  anomalyRate: 4.3,
  negativeRate: 8.7,
};

export const mockCompetitorProducts: CompetitorProduct[] = [
  {
    id: 'CP-001',
    name: 'Renpho Smart Scale ES-32',
    brand: 'Renpho',
    category: '体脂秤',
    specs: {
      售价: '$29.99',
      评分: '4.5',
      评论数: '125,000+',
      连接方式: '蓝牙4.0',
      测量项: '13项',
      APP评分: '4.3',
      传感器: '4电极ITO',
      电池: '3xAAA',
      承重: '180kg',
    },
  },
  {
    id: 'CP-002',
    name: 'Eufy Smart Scale P3',
    brand: 'Eufy (Anker)',
    category: '体脂秤',
    specs: {
      售价: '$45.99',
      评分: '4.6',
      评论数: '85,000+',
      连接方式: '蓝牙+WiFi',
      测量项: '16项',
      APP评分: '4.5',
      传感器: '4电极ITO',
      电池: '3xAAA',
      承重: '180kg',
    },
  },
  {
    id: 'CP-003',
    name: 'Withings Body+',
    brand: 'Withings',
    category: '体脂秤',
    specs: {
      售价: '$99.95',
      评分: '4.5',
      评论数: '60,000+',
      连接方式: '蓝牙+WiFi+NFC',
      测量项: '8项',
      APP评分: '4.7',
      传感器: '4电极ITO',
      电池: '内置充电',
      承重: '200kg',
    },
  },
  {
    id: 'CP-004',
    name: 'Hyperice Hypervolt 2 Pro',
    brand: 'Hyperice',
    category: '筋膜枪',
    specs: {
      售价: '$329',
      评分: '4.7',
      评论数: '28,000+',
      转速: '1700-2700 rpm',
      噪音: '55-65dB',
      电池: '3小时续航',
      重量: '1.2kg',
      档位: '5档',
    },
  },
];

export const mockMarketMonitor: MarketMonitorItem[] = [
  {
    id: 'MM-001',
    competitor: 'Renpho',
    product: 'ES-32 体脂秤',
    price: 29.99,
    rating: 4.5,
    reviewCount: 125000,
    bsr: 85,
    lastUpdated: '2026-06-23',
    change: '价格↓$2.00',
  },
  {
    id: 'MM-002',
    competitor: 'Eufy',
    product: 'P3 体脂秤',
    price: 45.99,
    rating: 4.6,
    reviewCount: 85000,
    bsr: 120,
    lastUpdated: '2026-06-23',
    change: 'BSR↓15位',
  },
  {
    id: 'MM-003',
    competitor: 'Withings',
    product: 'Body+ 体脂秤',
    price: 99.95,
    rating: 4.5,
    reviewCount: 60000,
    bsr: 210,
    lastUpdated: '2026-06-22',
    change: '新增NFC功能',
  },
  {
    id: 'MM-004',
    competitor: 'Hyperice',
    product: 'Hypervolt 2 Pro',
    price: 329,
    rating: 4.7,
    reviewCount: 28000,
    bsr: 45,
    lastUpdated: '2026-06-23',
    change: '评分↑0.1',
  },
  {
    id: 'MM-005',
    competitor: 'Theragun',
    product: 'Prime 筋膜枪',
    price: 299,
    rating: 4.6,
    reviewCount: 35000,
    bsr: 68,
    lastUpdated: '2026-06-22',
    change: '价格↑$20',
  },
];

export const mockSentimentItems: SentimentItem[] = [
  {
    id: 'SM-001',
    platform: 'TikTok',
    content: 'Renpho scale accuracy comparison with DEXA scan shows impressive results',
    sentiment: '正面',
    date: '2026-06-23',
    competitor: 'Renpho',
    keywords: ['精度', '对比', 'DEXA'],
  },
  {
    id: 'SM-002',
    platform: 'Reddit',
    content: 'Hyperice Hypervolt 2 Pro is way too loud for apartment use',
    sentiment: '负面',
    date: '2026-06-22',
    competitor: 'Hyperice',
    keywords: ['噪音', '公寓', '筋膜枪'],
  },
  {
    id: 'SM-003',
    platform: 'YouTube',
    content: 'Withings Body+ vs Eufy P3: Which smart scale is right for you?',
    sentiment: '中性',
    date: '2026-06-21',
    competitor: 'Withings',
    keywords: ['对比', '体脂秤', '评测'],
  },
  {
    id: 'SM-004',
    platform: 'Twitter',
    content: 'Just got the new Theragun Prime and the ergonomic design is a game changer',
    sentiment: '正面',
    date: '2026-06-20',
    competitor: 'Theragun',
    keywords: ['设计', '人体工学', '筋膜枪'],
  },
  {
    id: 'SM-005',
    platform: 'Instagram',
    content: 'Eufy P3 app keeps crashing during measurement sync. Frustrating!',
    sentiment: '负面',
    date: '2026-06-22',
    competitor: 'Eufy',
    keywords: ['APP', '崩溃', '同步'],
  },
];
