/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    DetailDrawer: typeof import('./components/common/DetailDrawer.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/common/StatsCard.vue')['default']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
  }
}
